CREATE TYPE STATUS AS ENUM (
    'PENDING',
    'PROCESSING',
    'SUCCESS',
    'FAILED'
);
CREATE CAST (VARCHAR AS STATUS) WITH INOUT AS IMPLICIT;
CREATE CAST (STATUS AS VARCHAR) WITH INOUT AS IMPLICIT;
