### UPLOAD Products CSV file
POST {{host}}/api/v1/products/csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="csv"; filename="products.csv"
Content-Type: text/plain

< ../data/products.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

> {%
    client.global.set("job_id", response.body.jobId)
%}}