// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greeting/v1/greeting.proto
// Protobuf Java Version: 4.34.1

package com.github.mangila.greeting.v1;

@com.google.protobuf.Generated
public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greeting.v1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
