quarkus.jacoco.report-location=target/jacoco-report
# Logging
quarkus.log.console.json.enabled=false
# JobRunr
quarkus.jobrunr.dashboard.enabled=false
# Management
quarkus.management.enabled=false
# Health
quarkus.smallrye-health.ui.enabled=false
# OpenApi
quarkus.swagger-ui.enabled=false
# Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true