# Devservices
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.port=5432
quarkus.datasource.devservices.username=${POSTGRES_USERNAME:changeit}
quarkus.datasource.devservices.password=${POSTGRES_PASSWORD:changeit}
# Logging
quarkus.log.console.json.enabled=false
# Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true