# Quarkus
## Datasource
## datasource: default
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
quarkus.datasource.username=${POSTGRES_USERNAME:changeit}
quarkus.datasource.password=${POSTGRES_PASSWORD:changeit}
# Logging
quarkus.log.console.json.enabled=true