# Quarkus
## HTTP
quarkus.http.enable-compression=true
quarkus.http.http2=true
## CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.exposed-headers=X-TRACE-ID,LOCATION
## Rest Client
quarkus.rest-client.alpn=true
### httpbin
quarkus.rest-client.httpbin.url=https://httpbin.org
## Hibernate
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.hibernate-orm.statistics=true
quarkus.hibernate-orm.log-session-metrics=true
quarkus.hibernate-orm.scripts.generation.create-target=target/generated.sql
quarkus.hibernate-orm.scripts.generation=create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.highlight-sql=true
### Hibernate: envers
quarkus.hibernate-envers.do-not-audit-optimistic-locking-field=true
quarkus.hibernate-envers.store-data-at-delete=true
quarkus.hibernate-envers.audit-table-suffix=_audit
## Datasource
## datasource: default
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
## datasource: pgjobrunr (JobRunr Storage Provider)
quarkus.datasource.pgjobrunr.db-kind=postgresql
quarkus.datasource.pgjobrunr.jdbc.driver=org.postgresql.Driver
## JobRunr
quarkus.jobrunr.job-scheduler.enabled=true
quarkus.jobrunr.background-job-server.enabled=true
quarkus.jobrunr.background-job-server.name=${quarkus.application.name}
quarkus.jobrunr.database.datasource=pgjobrunr
quarkus.jobrunr.dashboard.enabled=true
quarkus.jobrunr.dashboard.port=9001
## Flyway
quarkus.flyway.clean-disabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-version=1
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.table=flyway_schema_history
## RFC 9457
quarkus.resteasy.problem.include-mdc-properties=traceId
quarkus.resteasy.problem.constraint-violation.status=422
quarkus.resteasy.problem.constraint-violation.title=Constraint violation
quarkus.resteasy.problem.constraint-violation.description=Validation error
## Logging
quarkus.log.level=INFO
quarkus.log.console.enabled=true
quarkus.log.console.json.enabled=false
quarkus.log.console.json.log-format=ecs
quarkus.log.console.json.pretty-print=true
## Management
quarkus.management.enabled=true
quarkus.management.port=9000
## Health
quarkus.smallrye-health.ui.enabled=true
quarkus.smallrye-health.include-problem-details=true
## OpenApi
quarkus.swagger-ui.enabled=true