---
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: maven-validate-crud1-api-module
        name: Maven Validate Crud1
        entry: mise run //crud1:mvn-validate
        language: system
        files: ^crud1/api
        require_serial: true
        pass_filenames: false
        stages: [ pre-commit ]
      - id: maven-test-crud1-api-module
        name: Maven Test Crud1
        entry: mise run //crud1:mvn-test
        language: system
        files: ^crud1/api
        require_serial: true
        pass_filenames: false
        stages: [ pre-push ]
