experimental_monorepo_root = true

[settings]
experimental = true

[tools]
maven = "3.9.12"
python = "3.14.4"

[env]
_.python.venv = ".venv"

[tasks.megalint]
description = "Megalint with Java flavor"
run = "docker run --rm -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-java"