# Application Props
app.integration.pokeapi.token=${POKEAPI_TOKEN:changeit}
app.integration.pgevent.channels[0]=customer_evict
app.integration.pgevent.channels[1]=product_evict
app.integration.pgevent.channels[2]=order_evict
# Quarkus Props
quarkus.virtual-threads.enabled=true
# Container
quarkus.container-image.build=true
quarkus.container-image.builder=jib
quarkus.container-image.group=mangila
quarkus.container-image.name=customer-api
# HTTP
quarkus.http.port=8085
quarkus.http.limits.max-body-size=20M
quarkus.http.enable-compression=true
quarkus.http.http2=true
quarkus.http.body.delete-uploaded-files-on-end=false
quarkus.http.body.uploads-directory=target/uploads
# Camel
# Hibernate
quarkus.hibernate-orm.scripts.generation.create-target=target/generated.sql
quarkus.hibernate-orm.scripts.generation=create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.highlight-sql=true
# Postgres
## datasource: default
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
## datasource: pgevent (PostgreSQL LISTEN/NOTIFY)
quarkus.datasource.pgevent.db-kind=pgsql
quarkus.datasource.pgevent.driver=com.impossibl.postgres.jdbc.PGDriver
quarkus.datasource.pgevent.jdbc.url=jdbc:pgsql://localhost:5432/quarkus
quarkus.datasource.pgevent.username=postgres
quarkus.datasource.pgevent.password=postgres
## datasource: pgjobrunr (JobRunr Storage Provider)
quarkus.datasource.pgjobrunr.db-kind=postgresql
quarkus.datasource.pgjobrunr.jdbc.driver=org.postgresql.Driver
quarkus.datasource.pgjobrunr.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
quarkus.datasource.pgjobrunr.username=postgres
quarkus.datasource.pgjobrunr.password=postgres
# Flyway
quarkus.flyway.clean-disabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-version=1
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.table=customer_flyway_schema_history
# Customer: Cache
quarkus.cache.caffeine."customer".initial-capacity=10
quarkus.cache.caffeine."customer".maximum-size=100
quarkus.cache.caffeine."customer".expire-after-write=10M
# JobRunr
quarkus.jobrunr.database.table-prefix=customer_
quarkus.jobrunr.job-scheduler.enabled=true
quarkus.jobrunr.background-job-server.enabled=true
quarkus.jobrunr.background-job-server.name=${quarkus.application.name}
quarkus.jobrunr.database.datasource=pgjobrunr
quarkus.jobrunr.dashboard.enabled=true
quarkus.jobrunr.dashboard.port=9001
# Logging
quarkus.log.console.enabled=true
quarkus.log.console.json.enabled=false
quarkus.log.console.json.log-format=ecs
quarkus.log.console.json.pretty-print=true
# Native
# this option builds inside a container, might need to crank up the memory for the image build to not go out of memory(OOM).
quarkus.native.container-build=true
quarkus.native.resources.includes=db/migration/postgresql*.sql
# Management
quarkus.management.enabled=true
quarkus.management.port=9000
# Health
quarkus.smallrye-health.ui.enabled=true
quarkus.smallrye-health.include-problem-details=true
# OpenApi
quarkus.swagger-ui.enabled=true