# Quarkus

# Container
quarkus.container-image.build=true
quarkus.container-image.builder=jib
# HTTP
quarkus.http.port=8085

# Native
quarkus.native.enabled=true
quarkus.native.resources.includes=data.csv
quarkus.native.container-build=true
