quarkus.native.enabled=true
# this option builds inside a container, might need to crank up the memory, for the image build to not OOM.
quarkus.native.container-build=true
quarkus.container-image.name=customer-api-native
quarkus.native.resources.includes=data/**