# Devservices
quarkus.datasource.devservices.enabled=false
quarkus.datasource.devservices.port=5432
quarkus.datasource.devservices.username=postgres
quarkus.datasource.devservices.password=postgres
# Logging
quarkus.log.console.json.enabled=false
# Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true