# Application
app.secret=${ONE_SECRET:changeit}
app.integration.secret=${INTEGRATION_SECRET:changeit}
# Quarkus

# Container
quarkus.container-image.build=true
quarkus.container-image.builder=jib
quarkus.container-image.group=mangila
quarkus.container-image.name=customer-api
# HTTP
quarkus.http.port=8085
# Flyway
quarkus.flyway.clean-disabled=true
# Redis
# PokeApi
quarkus.rest-client.pokeapi.url=https://pokeapi.co/api/v2
quarkus.rest-client.pokeapi.http2=true
quarkus.rest-client.pokeapi.enable-response-decompression=true
quarkus.rest-client.pokeapi.logging.scope=all
# Health
quarkus.smallrye-health.ui.enabled=true
quarkus.smallrye-health.include-problem-details=true
# OpenApi
quarkus.swagger-ui.enabled=true
# Logging
quarkus.log.console.json.log-format=ecs
quarkus.log.console.json.pretty-print=true
quarkus.log.console.json.enabled=true

# TODO: remove this
# Tell Hibernate not to touch the database, just for build testing
quarkus.hibernate-orm.enabled=false