# MegaLinter configuration file
# More info at https://megalinter.io
# Configuration documentation: https://megalinter.io/latest/configuration/
# Linters documentation: https://megalinter.io/latest/descriptors/
---
APPLY_FIXES: all
VALIDATE_ALL_CODEBASE: true
PRINT_ALL_FILES: true
SHOW_ELAPSED_TIME: true
PARALLEL: true
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
ENABLE_LINTERS:
  - JAVA_CHECKSTYLE
  - JAVA_PMD
  - SQL_SQLFLUFF
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - JSON_PRETTIER

EXCLUDED_DIRECTORIES:
  - target
  - build
  - .quarkus
  - .venv
  - .idea
  - .git
  - node_modules
  - .astro
  - .scannerwork

PRE_COMMANDS:
  - command: npm install prettier-plugin-astro
    secured_env: true
    cwd: workspace
  - command: npm install prettier-plugin-tailwindcss
    secured_env: true
    cwd: workspace

JAVA_CHECKSTYLE_CONFIG_FILE: megalinter-config/google-checks.xml
JAVA_PMD_CONFIG_FILE: megalinter-config/pmd-ruleset.xml
SQL_SQLFLUFF_CONFIG_FILE: megalinter-config/sqlfluff.ini
JSON_PRETTIER_CONFIG_FILE: megalinter-config/.prettierrc.mjs
JSON_PRETTIER_FILE_EXTENSIONS: [".astro"]

# Reporting
LOG_LEVEL: DEBUG
SARIF_REPORTER: true
CONSOLE_REPORTER: true
# Human-readable reports
MARKDOWN_SUMMARY_REPORTER: true
