[tools]
java = "graalvm-community-25.0.2"
quarkus = "3.35.1"
node = "24.15.0"
k6 = "1.7.1"
sonar-scanner-cli = "8.1.0.6389"

[tasks.mvn-format]
description = "Format POM sorting and code formatting in api module"
run = [
    "mvn -f api/pom.xml sortpom:sort",
    "mvn -f api/pom.xml fmt:format",
]

[tasks.mvn-validate]
description = "Maven Validate goal in api module"
run = [
    "mvn -f api/pom.xml validate",
]

[tasks.mvn-verify]
description = "Maven Verify goal in api module"
run = [
    "mvn -f api/pom.xml verify",
]

[tasks.k6-read-write]
description = "Run k6 tests in api module"
dir = "tests/k6"
run = [
    "k6 run read-write-api-k6-test.js",
]

[tasks.k6-crud]
description = "Run k6 tests in api module"
dir = "tests/k6"
run = [
    "k6 run crud-lifecycle-k6-test.js",
]

[tasks.k6-bulk]
description = "Run k6 tests in api module"
dir = "tests/k6"
run = [
    "k6 run bulk-api-k6-test.js"
]

[tasks.megalint]
description = "Megalint with Java flavor"
run = "podman run --rm -v $(pwd):/tmp/lint:rw docker.io/oxsecurity/megalinter-java"

[tasks.sonarqube]
description = "Start SonarQube server on port 9050"
run = "podman run --rm -p 9050:9000 docker.io/sonarqube:lts-community"

[tasks."sonar:scan"]
description = "Run SonarQube analysis with JaCoCo coverage in api module"
dir = "api"
env = {
    SONAR_HOST_URL = "http://localhost:9050",
    SONAR_USERNAME = "admin",
    # note: need to change pw at first login
    SONAR_PASSWORD = "admin1"
}
run = """
sonar-scanner \
  -Dsonar.host.url=$SONAR_HOST_URL \
  -Dsonar.login=$SONAR_USERNAME \
  -Dsonar.password=$SONAR_PASSWORD \
"""