# Logging
quarkus.log.console.json.enabled=false
quarkus.log.category."org.hibernate.session.metrics".level=DEBUG
# Management
quarkus.management.enabled=false
# Health
quarkus.smallrye-health.ui.enabled=false
# OpenApi
quarkus.swagger-ui.enabled=false
# Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true