quarkus.openshift.deployment-kind=Job
quarkus.container-image.builder=docker
quarkus.native.container-build=true
quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.group=mangila
quarkus.container-image.name=web2
quarkus.container-image.tag=latest
quarkus.openshift.add-name-to-label-selectors=false
quarkus.openshift.add-version-to-label-selectors=false