// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greeting/v1/greeting.proto
// Protobuf Java Version: 4.34.1

package com.github.mangila.greeting.v1;

@com.google.protobuf.Generated
public final class GreetingProto extends com.google.protobuf.GeneratedFile {
  private GreetingProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "GreetingProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greeting_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_greeting_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greeting_v1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_greeting_v1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032greeting/v1/greeting.proto\022\013greeting.v" +
      "1\"\"\n\014HelloRequest\022\022\n\004name\030\001 \001(\tR\004name\")\n" +
      "\rHelloResponse\022\030\n\007message\030\001 \001(\tR\007message" +
      "2S\n\017GreetingService\022@\n\005Hello\022\031.greeting." +
      "v1.HelloRequest\032\032.greeting.v1.HelloRespo" +
      "nse\"\000B|\n\036com.github.mangila.greeting.v1B" +
      "\rGreetingProtoP\001\242\002\003GXX\252\002\013Greeting.V1\312\002\013G" +
      "reeting\\V1\342\002\027Greeting\\V1\\GPBMetadata\352\002\014G" +
      "reeting::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_greeting_v1_HelloRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_greeting_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_greeting_v1_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_greeting_v1_HelloResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_greeting_v1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_greeting_v1_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
