// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greeting/v1/greeting.proto
// Protobuf Java Version: 4.34.1

package com.github.mangila.greeting.v1;

@com.google.protobuf.Generated
public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greeting.v1.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
