[tools]
java = "graalvm-community-25.0.2"
quarkus = "3.32.4"

[tasks.jvm]
description = "Build JVM Quarkus image with Jib"
run = "quarkus build"
dir = "api"

[tasks.native]
description = "Build native Quarkus image with Jib"
run = "quarkus build --native -Dquarkus.container-image.name=qtest-native"
dir = "api"
