sonar.projectKey=web1-api
sonar.projectName=web1-api
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
sonar.sourceEncoding=UTF-8