fail_fast: false
repos:
  - repo: local
    hooks:
      - id: maven-sortpom-verify
        name: Maven Sort POM Verify
        entry: mvn
        args: [ "-f", "crud1/api/pom.xml", "sortpom:verify" ]
        language: system
        files: ^crud1/api/pom.xml$
        require_serial: true
        pass_filenames: false
      - id: maven-fmt
        name: Maven Fmt
        entry: mvn
        args: [ "-f", "crud1/api/pom.xml", "fmt:check" ]
        language: system
        require_serial: true
        pass_filenames: false