[tools]
java = "graalvm-community-25.0.2"
quarkus = "3.35.1"

[tasks.mvn-verify-format]
description = "Verify POM sorting and code formatting in crud1 api module"
run = [
    "mvn -f api/pom.xml sortpom:verify",
    "mvn -f api/pom.xml fmt:check",
]

[tasks.mvn-format]
description = "Format POM sorting and code formatting in crud1 api module"
run = [
    "mvn -f api/pom.xml sortpom:sort",
    "mvn -f api/pom.xml fmt:format",
]
