[tools]
java = "graalvm-community-25.0.2"
quarkus = "3.35.1"

[tasks.mvn-format]
description = "Format POM sorting and code formatting in api module"
run = [
    "mvn -f api/pom.xml sortpom:sort",
    "mvn -f api/pom.xml fmt:format",
]

[tasks.mvn-test]
description = "Maven test in api module"
run = [
    "mvn -f api/pom.xml test",
]

[tasks.api-k6]
description = "Run k6 tests in api module"
run = [
    "k6 run k6/read-write-api-k6-test.js"
]
